### ISSUE TITLE
Error message about "Cannot find module '~/...'."

### ISSUE THREAD

**Issue by jmeinke** [iliyaZelenko/tiptap-vuetify#1]
Thanks for this package. I get the following TypeScript error message using it:
```
2:36 Cannot find module '~/configs/theme'.
    1 | import MainComponent from '~/components/Main.vue';
  > 2 | import { VuetifyIconsGropus } from '~/configs/theme';
      |                                    ^
    3 | export declare const TiptapVuetify: import("vue").VueConstructor<MainComponent>;
    4 | export declare const TiptapVuetifyPlugin: {
    5 |     iconsGroup: VuetifyIconsGropus;
```

This message appears for all imports and exports in main.d.ts.
What can I do?

**Comment by iliyaZelenko** [comment]
@jmeinke Hi, thank you very much for the error and the first star! If you did not inform me about this, I would not know about it and people would fall for this error.

I guessed it would cause a problem. This is not a correctly generated path: "~" should point to the "src" folder. 

I will try to solve this problem today, at least in the near future. Thanks again!

**Comment by iliyaZelenko** [comment]
@jmeinke I solved this problem, I will soon release a new version and let you know about it. I want to hear from you feedback whether it will work.

**Comment by iliyaZelenko** [comment]
@jmeinke  everything is ready and I think everything will work for you. You can install the `1.3.5` version. 

Thank you for using this package. I hope I did not delay you much.

**Comment by jmeinke** [comment]
Hey @iliyaZelenko, no worries and thanks a lot! You can close this. The fix you have committed works, but now there are new / other problems. Please see #2.
