### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by sandroden** [iliyaZelenko/tiptap-vuetify#10]
Is there a way to add placeholders? 
TipTap has this possibility via the Placeholder object that seems to be missing in tiptap-vuetify... btw I personally think that it would be nicer to have a more reusable syntax than what offered by tiptap. In a typical case when you have the same toolbar you have to re-declare all extension just to add a Placeholder that is typically different in each editor.

**Comment by iliyaZelenko** [comment]
Thanks for the suggestion.

This is implemented via the `placeholder` prop now. [Demo](https://codesandbox.io/s/p2wnzxyo90?fontsize=14&initialpath=%2Fplaceholder&module=%2Fsrc%2Fexamples%2FPlaceholder.vue).
