### ISSUE TITLE
KeyPress Event

### ISSUE THREAD

**Issue by Bojoofu** [iliyaZelenko/tiptap-vuetify#100]
I was wondering how I can attach a custom key press event? I've tried looking over the docs and wasn't able to find anything.  I tried looking at the issues and nothing similar was asked.

**Comment by Bojoofu** [comment]
So, I have been able to find out how to attach a key press handler after playing around much more!  But the I am now having an issue where when I press the enter key, the handler doesn't trigger.  I would like to add a custom handler when the users presses the enter key while typing.

Here is my component 

```js
<tiptap-vuetify
    v-model="message"
    :extensions="extensions"
    placeholder="Message..."
    :card-props="{ flat: true }"
    :editor-properties="{
        editorProps:{
            handleKeyDown: (view, event) => {
                this.handleKey(event)
                this.handleKey(view)
                
                if (event.key === 'Enter') {
                    // do something
                    return true
                }

                return false
            }
        }
    }"
/>
```

`this.handleKey(<parameter>)` just calls a Vue method to log to the console the **parameter** being passed to it.

Is this the correct way of adding a custom handler for when a users presses the **Enter** key, or is there a better way?

**Comment by iliyaZelenko** [comment]
This is the only way to track a keypress event.

After your message, I have plans to simplify this, to use Vue's events on the component, e.g:
``` vue
<tiptap-vuetify
    v-model="message"
    :extensions="extensions"
    @keydown="keydownHandler"
    @keypress="keypressHandler"
/>
```

Glad you found the answer, I wanted to write you an hour ago, I knew the answer, but I was a little busy.

**Comment by iliyaZelenko** [comment]
I spent time searching and found how to do it in tiptap. Here's how it works through my package:

``` js
import { Extension } from 'tiptap'
```

Add your extension to `nativeExtensions`:

``` js
  data: () => ({
    extensions: [],
    nativeExtensions: [
      new class extends Extension {
        keys () {
          return {
            Enter (state, dispatch, view) {
              console.log('Enter!')
              // return true prevents default behaviour
              return true
            }
          }
        }
      }()
    ],
    content: 'test'
  }),
```

Use `nativeExtensions` via `native-extensions` prop:

``` vue
    <tiptap-vuetify
      v-model="content"
      :native-extensions="nativeExtensions"
      :extensions="extensions"
    />
```

Such a difficult decision only with the <kbd>Enter</kbd>, I don’t know why.

**Comment by iliyaZelenko** [comment]
I released a new version `2.7.0`, in which you can use [`keydown`](https://github.com/iliyaZelenko/tiptap-vuetify#keydown) event if needed.

**Comment by Bojoofu** [comment]
No worries at all and I have successfully implemented your suggestion and it works as designed!  Thank you very much!  Now I can use your amazing editor for creating messages! 😃

**Comment by Bojoofu** [comment]
I spoke a little too soon haha.  I have a method that resides in the main component that I would like to call when the user presses enter (from within the `Enter` method in the custom native extension). I tried calling it but it returns undefined.  I know I'm missing something but I cannot put my finger on it.

**Comment by iliyaZelenko** [comment]
`this.sendMessage` is undefined because because it is a different context  (`this`). Try arrow function:

```js
Enter: (state, dispatch, view) => {
  this.sendMessage();

  return true
}
```

**Comment by Bojoofu** [comment]
Just tested it out and seems that it's not a function
> _this2.sendMessage is not a function

**Comment by Bojoofu** [comment]
I was able to play around with it deeper and got it to work correctly after your massive hint! Thank you for that!!!!


I made a new JS file that held my custom extension in it to handle the **Enter** key press. I imported that into the component that I was using and instanciated a new instance of the extension class in the **nativeExtensions** data element.  From there I passed a reference to the desired class in the component as an option to the extension.

### Component
```js
import SendMessage from './sendMessage'

export default {
    data() {
        return {
            nativeExtensions: [
                new SendMessage({
                    sendMessage: () => this.sendMessage()
                }
            ]
        }
    },

    methods: {
        sendMessage() {...}
    }
}
```

### Extension Class
```js
import { Extension } from 'tiptap'

export default class SendMessage extends Extension {
    keys() {
        return {
            Enter: (state, dispatch, view) => {
                this.options.sendMessage();

                return true
            }
        }
    }
}
```


Thanks again for all of the help and speedy replies!!!! 😃

**Comment by CP-4** [comment]
> This is the only way to track a keypress event.
> 
> After your message, I have plans to simplify this, to use Vue's events on the component, e.g:
> 
> ```
> <tiptap-vuetify
>     v-model="message"
>     :extensions="extensions"
>     @keydown="keydownHandler"
>     @keypress="keypressHandler"
> />
> ```
> 
> Glad you found the answer, I wanted to write you an hour ago, I knew the answer, but I was a little busy.

Hey, is the above mentioned @keydown method working, or do i need to use :nativeExtension for getting keydown events?
