### ISSUE TITLE
 Please add the modules Table

### ISSUE THREAD

**Issue by smman89** [iliyaZelenko/tiptap-vuetify#107]
Please add the modules Table, TableHeader, TableCell, TableRow

**Comment by iliyaZelenko** [comment]
Yes, it’s worth adding. I plan to add in two weeks.

Main issue: https://github.com/iliyaZelenko/tiptap-vuetify/issues/20

**Comment by fabioebner** [comment]
@iliyaZelenko 
Did you add the table module? 

tks

**Comment by iliyaZelenko** [comment]
@fabioebner answered [here](https://github.com/iliyaZelenko/tiptap-vuetify/issues/20#issuecomment-575180678).
