### ISSUE TITLE
Markdown editor example

### ISSUE THREAD

**Issue by fredekiel** [iliyaZelenko/tiptap-vuetify#109]
Hey there

Could you create an example for a markdown editor?

I only see html and json as output-format options. Would you use json? If so how would you display it to the user

**Comment by iliyaZelenko** [comment]
Here an example of markdown shortcuts: https://tiptap.scrumpy.io/markdown-shortcuts

As far as I know JSON export (JSON data) more flexible, but if you do not see the point, then you probably do not need it.

**Comment by fredekiel** [comment]
That's only shortcuts :( I need a full markdown editor. Where the output is markdown and not html

**Comment by iliyaZelenko** [comment]
Related issue: https://github.com/scrumpy/tiptap/issues/66
