### ISSUE TITLE
Shift-enter newline while using "code" doesn't display properly

### ISSUE THREAD

**Issue by fredekiel** [iliyaZelenko/tiptap-vuetify#111]
When you're writing a code block and shift-enter for newline the cursor stays at the first line instead of going to the new one. It switches once you start typing. (See image for example)
![Editor code block newline](https://i.imgur.com/D3QOLYv.png)

Creating a code block in the middle of a row will also not break to a new line. This will look a little funny if you create new lines within the code block
![Editor code block newline](https://i.imgur.com/4XiN0Cc.png)

OS: Windows 10
Browser: Chrome v78.0.3904.108 + Firefox v70.0.1

**Comment by iliyaZelenko** [comment]
Are you sure this is extension `CodeBlock`? There are two extensions: `CodeBlock` and `Code`. In my demo, only `Code` is used as i see.

**Comment by fredekiel** [comment]
> Are you sure this is extension `CodeBlock`? There are two extensions: `CodeBlock` and `Code`. In my demo, only `Code` is used as i see.

I was using the regular code 😅 but the behavior is still a little odd. I assume it's got something to do with the tiptap core?

**Comment by iliyaZelenko** [comment]
> I assume it's got something to do with the tiptap core?

Yes, or Prosemirror. My package is only wrapper with vuetify components.
