### ISSUE TITLE
[Bug] List items are created with paragraphs

### ISSUE THREAD

**Issue by fredekiel** [iliyaZelenko/tiptap-vuetify#112]
Not sure if this is a bug, but maybe list items shouldn't be created with paragraphs as the inner HTML? It creates a very large spacing between the list items.

Look at the image comparing quotes(blue) vs. lists(red)
![List item spacing](https://i.imgur.com/wkP2vbO.jpg)

**Comment by iliyaZelenko** [comment]
This editor is based on [tiptap](https://github.com/scrumpy/tiptap), which in turn is based on [prosemirror](https://prosemirror.net/). 

This behavior can be seen in prosemirror. Therefore, it is better to ask them on the github.

**Comment by iliyaZelenko** [comment]
Related issue https://github.com/scrumpy/tiptap/issues/118
