### ISSUE TITLE
TypeError: Cannot read property 'framework' of undefined

### ISSUE THREAD

**Issue by ziad-akiki** [iliyaZelenko/tiptap-vuetify#113]
Hello, after updating to `vuetify@2.1.14`, the tiptap vuetify editor is not being loaded with the following error in the console:
> Error in mounted hook: "TypeError: Cannot read property 'framework' of undefined"

Specifically, it is being thrown in this specific code block in `TiptapVuetifyPlugin` source :
```
Object.defineProperty(Plugin.prototype, "vuetifyLang", {
    get: function get() {
      return this.vuetify.framework.lang.current; // This line
    },
    enumerable: true,
    configurable: true
  });
```
So typically I checked if the `vuetify` object passed in the [Initialization section](https://github.com/iliyaZelenko/tiptap-vuetify#npm-es-modules) is really `undefined` by logging it to the console, but the output is a Vuetify object as expected.

Transpilation is enabled as well in `vue.config.js` and removing it did not solve the issue:
```
transpileDependencies: ['vuetify','tiptap-vuetify'],
```

Concerning the packages' versions (in case they might come in handy, I selected the main ones):
```
"babel-polyfill": "^6.26.0",
"core-js": "^3.4.8",
"tiptap-vuetify": "^2.8.0",
"vue": "^2.6.10",
"vuetify": "^2.1.14"
```

**Comment by iliyaZelenko** [comment]
Thanks for the detailed error description. I will try to look at it in more detail in the near future.

**Comment by deluciame** [comment]
Same issue here with "vuetify": "^2.1.12",

**Comment by 13enedict** [comment]
In case this helps anyone, I got this error after accidentally removing `Vue.use(TiptapVuetifyPlugin, {vuetify})` from my project
