### ISSUE TITLE
BulletList and OrderedList broken

### ISSUE THREAD

**Issue by rataman098** [iliyaZelenko/tiptap-vuetify#119]
Hey there!

When I add BulletList or OrderedList to my component, it suddently disappears. In console appears an error:

`SyntaxError: "No node type or group 'list_item' found (in content expression 'list_item+')"`

Any idea about which could be the cause? Thanks in advance 😄

**Comment by iliyaZelenko** [comment]
Hi, @rataman098! Sorry for the late reply.

You also needed to use `ListItem`. Sorry for the inaccuracy of the documentation, now I [updated it](https://github.com/iliyaZelenko/tiptap-vuetify/commit/2488e713417da9beb70e193ed4f9fc4e391c2166).
