### ISSUE TITLE
How to load tiptap only when necessary, not in application entry point (main.js)

### ISSUE THREAD

**Issue by flahol** [iliyaZelenko/tiptap-vuetify#123]
Tiptap is a great plugin for editing html text field.
However the installation, which is very straight forward, loads this plugin in the main.js file, that means it is loaded even if you don't need tiptap right-away.

Is there a way to load tiptap only on certain pages, like a regular component ?

Installation
```

import Vue from 'vue'
import Vuetify from 'vuetify'
// import plugin
import { TiptapVuetifyPlugin } from 'tiptap-vuetify'
// don't forget to import CSS styles
import 'tiptap-vuetify/dist/main.css'
// Vuetify's CSS styles 
import 'vuetify/dist/vuetify.min.css'


// Vuetify Object (as described in the Vuetify 2 documentation)
const vuetify = new Vuetify()

// use Vuetify's plugin
Vue.use(Vuetify)
// use this package's plugin
Vue.use(TiptapVuetifyPlugin, {
  // the next line is important! You need to provide the Vuetify Object to this place.
  vuetify, // same as "vuetify: vuetify"
  // optional, default to 'md' (default vuetify icons before v2.0.0)
  iconsGroup: 'md'
})
```
I wish there were no tiptap import in main.js but only on specific pages.
So basically how to convert tiptap plugin to a  tiptap component

**Comment by iliyaZelenko** [comment]
You already asked this question in the email, below will be the same answer. If you find a working solution, then write. I am closing this issue for now, as my answer should work.

I think this is what you need: https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components  
This can also help: https://router.vuejs.org/guide/advanced/lazy-loading.html

So I think you need to create separated component, use your code above here to register plugin, and than lazy-loading this component on pages you need. Something like this.

**Comment by GabrielBuragev** [comment]
@flahol I found a solution for this using **@nuxtjs/vuetify** & **tiptap-vuetify**

1. Write a plugin inside plugins that will initialize the plugin & install the component to the Vue instance 

- **plugins/tiptapVuetify.js**

```
import Vue from "vue";
import { TiptapVuetifyPlugin, TiptapVuetify } from "tiptap-vuetify";
export default vuetify => {
  if (!Vue.options.components.TiptapVuetify) {
    Vue.use(TiptapVuetifyPlugin, {
      vuetify: { ...vuetify, framework: { lang: vuetify.lang } },
      iconsGroup: "mdi",
    });
    Vue.component("TiptapVuetify", TiptapVuetify);
  }
  return;
};
```

2. Then inside component 
- **RichTextEditor.vue**

```
<template>
  <tiptap-vuetify v-if="tiptapLoaded" />
</template>

<script>
import tiptapVuetifyPlugin from "~/plugins/tiptapVuetify";
export default {
  created() {
    tiptapVuetifyPlugin(this.$vuetify);
    this.tiptapLoaded = true;
  },
</script>
```
