### ISSUE TITLE
ToDo Extension Support

### ISSUE THREAD

**Issue by douglasg14b** [iliyaZelenko/tiptap-vuetify#127]
Title says it all, can support for `TodoItem` & `TodoList` be added?

Thanks!

**Comment by iliyaZelenko** [comment]
Sorry that this was a little delayed, but I did it specifically for you. It is available in version `2.13.1`.

![](https://user-images.githubusercontent.com/13103045/74818484-6c980500-5307-11ea-9c45-5e5f73170bc5.png)

**Comment by douglasg14b** [comment]
Thanks!
