### ISSUE TITLE
How to add Alignment Button to Native Extensions 

### ISSUE THREAD

**Issue by limsocheat** [iliyaZelenko/tiptap-vuetify#128]
I found following issue for adding Text Alignment to editor. 
https://github.com/scrumpy/tiptap/issues/157

But no idea how to implement on tiptap-vuetify.
already follow this doc, but no luck 
https://github.com/iliyaZelenko/tiptap-vuetify#native-extensions

**Comment by joweste** [comment]
Hi, I have the same problem. Do you solved it?

**Comment by iliyaZelenko** [comment]
Duplicate of https://github.com/iliyaZelenko/tiptap-vuetify/issues/218
