### ISSUE TITLE
Duplicate use of selection JSON ID gapcursor

### ISSUE THREAD

**Issue by koekaverna** [iliyaZelenko/tiptap-vuetify#131]
When I add these line
```
import { TiptapVuetifyPlugin } from 'tiptap-vuetify'
```
I have error:
```
index.js?6ffb:192 Uncaught RangeError: Duplicate use of selection JSON ID gapcursor
    at Function.jsonID (index.js?6ffb:192)
    at eval (index.js?cdd8:87)
    at Object../node_modules/tiptap-extensions/node_modules/prosemirror-gapcursor/dist/index.js (chunk-vendors.js:4271)
    at __webpack_require__ (app.js:791)
    at fn (app.js:151)
    at eval (tiptap.esm.js?afc7:1)
    at Module../node_modules/tiptap-extensions/node_modules/tiptap/dist/tiptap.esm.js (chunk-vendors.js:4283)
    at __webpack_require__ (app.js:791)
    at fn (app.js:151)
    at eval (extensions.esm.js?f23d:1)
```

    "vue": "2.6.11",
    "vuetify": "2.2.4",
    "tiptap-vuetify": "2.10.0",

**Comment by Elrinth** [comment]
I can confirm tiptap-vuetify no longer works with current version of vue and vuetify.

**Comment by PhilippeSteinbach** [comment]
Same behaviour here. Also tried different versions of vuetify and/or tiptap-vuetify, but without success.

**Comment by iliyaZelenko** [comment]
Most likely you are importing extensions from `tiptap-extensions` in addition to importing from `tiptap-vuetify`. 

[Here](https://discuss.prosemirror.net/t/duplicate-use-of-selection-json-id-cell-error/2071/3) is the cause of the error: 
> The most likely cause is that you’re accidentally loading two different versions of prosemirror-tables, both of which are trying to register "cell" as identifying a cell selection in JSON output.

What do you import from `tiptap-extensions`?

Maybe [this ](https://github.com/scrumpy/tiptap/issues/316) will help.

[Demo of this package](https://codesandbox.io/s/vue-template-6p9wp?fontsize=14&module=%2Fsrc%2Fexamples%2FSimple.vue) works even when I updated packages versions there.

**Comment by PhilippeSteinbach** [comment]
Actually I didn't import anything from `tiptap-extensions`.
I created a new hello-world via VueCLI, added Vuetify and then followed the Installation and Getting Started section.

As soon as this line is being added to main.js
`import { TiptapVuetifyPlugin } from 'tiptap-vuetify'`
the same error that @koekaverna reported will be thrown.

**Comment by PhilippeSteinbach** [comment]
@Elrinth perfectly described the reproduction steps in anothet issue:
https://github.com/scrumpy/tiptap/issues/587

**Comment by jreal425** [comment]
@PhilippeSteinbach I can confirm that works. Thanks!

**Comment by flahol** [comment]
I have the same problem but I can't solve it  

I deleted in yarn.lock 
```
prosemirror-gapcursor@1.1.2:
  version "1.1.2"
  resolved "https://registry.yarnpkg.com/prosemirror-gapcursor/-/prosemirror-gapcursor-1.1.2.tgz#a1400a86a51d4cccc065e68d5625a9fb5bc623e0"
  integrity sha512-Z+eqk6RysZVxidGWN5aWoSTbn5bTHf1XZ+nQJVwUSdwdBVkfQMFdTHgfrXA8W5MhHHdNg/EEEYG3z3Zi/vE2QQ==
  dependencies:
    prosemirror-keymap "^1.0.0"
    prosemirror-model "^1.0.0"
    prosemirror-state "^1.0.0"
    prosemirror-view "^1.0.0"
```
and renamed
```
tiptap@^1.26.6:
  version "1.26.6"
  resolved "https://registry.yarnpkg.com/tiptap/-/tiptap-1.26.6.tgz#b287fa7cb1c20690868aee8dc526de5390b054f0"
  integrity sha512-U5qyYZi5IH7LhYwYrStRBp5MxF5MiGFLt9ogOAF/0N/LIg0XwVwe/AaSx0UH/s4dY7R8OvEa9u4qimO08Wp1LA==
  dependencies:
    prosemirror-commands "1.1.2"
    prosemirror-dropcursor "1.3.2"
    prosemirror-gapcursor "1.1.2"
```
to
```
tiptap@^1.26.6:
  version "1.26.6"
  resolved "https://registry.yarnpkg.com/tiptap/-/tiptap-1.26.6.tgz#b287fa7cb1c20690868aee8dc526de5390b054f0"
  integrity sha512-U5qyYZi5IH7LhYwYrStRBp5MxF5MiGFLt9ogOAF/0N/LIg0XwVwe/AaSx0UH/s4dY7R8OvEa9u4qimO08Wp1LA==
  dependencies:
    prosemirror-commands "1.1.2"
    prosemirror-dropcursor "1.3.2"
    prosemirror-gapcursor "1.1.3"
```
When I install tiptap-vuetify, yarn gives a warning
```
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "tiptap-vuetify > tiptap-extensions > prosemirror-utils@0.9.6" has incorrect peer dependency "prosemirror-tables@^0.9.1".
[4/4] Building fresh packages...
...
```

**Comment by iliyaZelenko** [comment]
As @Elrinth wrote [here](scrumpy/tiptap#587):
> Fork this or create a new Codesandbox replicating your error
https://codesandbox.io/s/qxv5m9y6oq?fontsize=14

I saw a error there. I just updated the packages to the latest versions and it worked: 
- `tiptap` 1.26.6
- `tiptap-extensions` 1.28.6

[Here](https://codesandbox.io/s/vue-issue-template-uy2py) is the same but working example.

And judging by this codesandbox, the reason is not in my tiptap-vuetify package, but in the [tiptap ](https://github.com/scrumpy/tiptap) package.

Who did not see, maybe [this](https://github.com/iliyaZelenko/tiptap-vuetify/issues/131#issuecomment-578664304) @PhilippeSteinbach's solution will help you.

**Comment by iliyaZelenko** [comment]
Oh yes try just adding these packages to your dependencies manually: `tiptap`, `tiptap-extensions`. This will deliver the latest versions of these packages and should fix the problem.

I noticed that I have a strange range of versions in this package:

```
  "dependencies": {
    "tiptap": "1.16.2",
    "tiptap-extensions": "^1.14.0"
  }
```

**Comment by iliyaZelenko** [comment]
In new version `2.11.1` everything should work now.

**Comment by flahol** [comment]
I confirm version 2.11.1 solves the problem, congratulations @iliyaZelenko  and thanks

**Comment by flahol** [comment]
I have a new problem, not sure it comes from this module.
It works except that I cannot add a new line when I hit ENTER although it works if I put the cursor between 2 letters.
The error message is :
`RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)`
I have 2 dependencies : prosemirror-model 1.9.1 and prosemirror-model 1.8.2
