### ISSUE TITLE
Write custom extension and integrate it into editor toolbar

### ISSUE THREAD

**Issue by t-itzel** [iliyaZelenko/tiptap-vuetify#132]
How can I write a custom extension and integrate it into tiptap-vuetify editor? 

The custom command must be integrated into the editors toolbar next to all other commands.

There is no nativeExtension from scrumpy/tip-tap which I could use via editor attribute `nativeExtensions,` I need to implement a completely custom extension.

**Comment by iliyaZelenko** [comment]
> There is no nativeExtension from scrumpy/tip-tap which I could use via editor attribute nativeExtensions

As shown in [example ](https://github.com/iliyaZelenko/tiptap-vuetify#native-extensions) of `nativeExtensions`, you need to import this extensions from 'tiptap-extensions' package, e.g.:

``` js
import {
  TrailingNode
} from 'tiptap-extensions'
```

> The custom command must be integrated into the editors toolbar next to all other commands.

By default, native extensions themselves will not add a command to the toolbar.

For now I did not create an example of how to do this. As one of the variants, [you can manually display the toolbar as you want](https://github.com/iliyaZelenko/tiptap-vuetify#toolbar), add your buttons there, etc.

**Comment by t-itzel** [comment]
Rendering the toolbar on my own helps.

Thank you for the hint :)
