### ISSUE TITLE
Error new line in v 2.11.1 prosemirror-model duplicates

### ISSUE THREAD

**Issue by flahol** [iliyaZelenko/tiptap-vuetify#134]
In version 2.11.1 there is a little bug.

When you hit ENTER for a new line it does not work and throws an error.
Although it works if the cursor is not at the end but between 2 letters.

Error message :
`RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)`
I have 2 dependencies : prosemirror-model 1.9.1 and prosemirror-model 1.8.2

**Comment by iliyaZelenko** [comment]
Try to delete `node_modules` folder and lock file. If you have `prosemirror-model` in your `package..json`, it’s better to remove it, unnecessary packages should go with my package `tiptap-vuetify`. And I think you should not have two different versions of `prosemirror-model`.

**Comment by iliyaZelenko** [comment]
I see this problem in my demo. Ok, I will think.

**Comment by iliyaZelenko** [comment]
I tried to [solve](https://github.com/iliyaZelenko/tiptap-vuetify/commit/9c679e4e6d7d8ecfdea28ca7cee39fa1835fc1f9) this problem at the level of my package, but it failed. You must manually do what is written in the [solution ](https://github.com/scrumpy/tiptap/issues/577) for your project.
