### ISSUE TITLE
Bubble menu incorrect position

### ISSUE THREAD

**Issue by jnyblom** [iliyaZelenko/tiptap-vuetify#136]
The bubble menu is incorrectly positioned when using v-app-bar and/or v-navigation-drawer. See [tiptap-vuetify-demo/#/bubble-menu](https://iliyazelenko.github.io/tiptap-vuetify-demo/#/bubble-menu). Selecting text renders bubble at the bottom of the browser, not at the selection as expected.

**Comment by iliyaZelenko** [comment]
I saw such a problem. Now it'ss on the first priority.

**Comment by iliyaZelenko** [comment]
Fixed in v2.12.2. Now works like a charm: https://iliyazelenko.github.io/tiptap-vuetify-demo/#/bubble-menu
