### ISSUE TITLE
Persistend extension hint on v-dialog open 

### ISSUE THREAD

**Issue by ctmqwe** [iliyaZelenko/tiptap-vuetify#138]
TitapVuetify component inside v-dialog in child component.
On dialog appearing in Tiptap component always showing hint - first extension. 
Hint closes after esc or clicking inside Tiptap component

Screens of opened dialog component
https://www.imageupload.net/image/RwCma
https://www.imageupload.net/image/RwJk2

**Comment by iliyaZelenko** [comment]
I seem to understand this, but not sure. It would be great if you provided a reproduction where I could see it and take further action. Perhaps this is also a bug in Vuetify itself.

**Comment by ctmqwe** [comment]
Using click function in v-text-field create bug:
`          v-col
            v-text-field(v-model="Text" @click="dialogText = true")
            dialog(v-model="dialogText")`
that variant workes fine:
`          v-col(@click="dialogText = true")
            v-text-field(v-model="Text")
            dialog(v-model="dialogText")`

In Sandbox working code, but sandbox not working 
https://codesandbox.io/s/wispy-dew-hwocp
