### ISSUE TITLE
Error using CDN version of package

### ISSUE THREAD

**Issue by AntonioLoureiro** [iliyaZelenko/tiptap-vuetify#139]
I get the error: please, specify in options the Vuetify Object ("vuetify" property).

Using the CDN version including the following scripts:

```
<script src="https://cdn.jsdelivr.net/npm/tiptap@1.26.6/dist/tiptap.min.js"></script>
<script src="https://unpkg.com/tiptap-vuetify@2.13.2/dist/bundle-umd.js"></script>
```

**Comment by iliyaZelenko** [comment]
You should have [`Vuetify` object](https://vuetifyjs.com/ru/getting-started/quick-start#cdn-usage) in `window.vuetify` property, then this error will disappear. Could you please try?

```
window.vuetify = new Vuetify()
```

Try writing this code before this script:

```
<script src="https://unpkg.com/tiptap-vuetify@2.13.2/dist/bundle-umd.js"></script>
```

**Comment by AntonioLoureiro** [comment]
It works now! thks
