### ISSUE TITLE
Solutions for upload image from string data

### ISSUE THREAD

**Issue by TrietPham96** [iliyaZelenko/tiptap-vuetify#141]
Hi @iliyaZelenko , i build blog project use vuetify and the tiptap-vuetify work pefect for me. I add function upload image to editor and it work good, however i can not post data object because all image when upload will genarate to base64 and it makes string data object very very long. How to upload content my post include all image via model object string data. Can you let me know approach for this case, please. Thank you very much

**Comment by iliyaZelenko** [comment]
Hi, @TrietPham96. Yes, pictures are now loaded through the base64, as it was originally in the tiptap itself. Unfortunately, this cannot yet be changed in an easy way. In the future, it is planned to improve this process. I wrote about it [here](https://github.com/iliyaZelenko/tiptap-vuetify/issues/16#issuecomment-549178917).

**Comment by TrietPham96** [comment]
Yes, i will wait. Please keep good working. Thank you for the nice work of community
