### ISSUE TITLE
ts support

### ISSUE THREAD

**Issue by alloself** [iliyaZelenko/tiptap-vuetify#143]
i think its not be easy declare this plugin with that vuetify installation

`import vuetify from './plugins/vuetify';
new Vue({
  vuetify,
})
`
or may be u can show how it can be work with it?

thanks!

**Comment by iliyaZelenko** [comment]
[Here ](https://github.com/iliyaZelenko/tiptap-vuetify-demo)is a full demo, a complete project. [Here ](https://github.com/iliyaZelenko/tiptap-vuetify-demo/blob/master/src/main.js#L14)is a line that uses imported `vuetify`.
