### ISSUE TITLE
Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)

### ISSUE THREAD

**Issue by paulvonber** [iliyaZelenko/tiptap-vuetify#144]
Is there any solution to this error? at the moment seems like it's totally unusable
![image](https://user-images.githubusercontent.com/37245111/75896228-09de5780-5e37-11ea-9245-88c5756adb49.png)

It happens when you want to use blockquote and bullet list also on break

**Comment by iliyaZelenko** [comment]
Duplicate of #134.
