### ISSUE TITLE
<script> import: How to get it working?

### ISSUE THREAD

**Issue by djhuistra** [iliyaZelenko/tiptap-vuetify#146]
I'm trying to get an import via script tag working, but I have no success so far. I get a ` Cannot read property 'Editor' of undefined` TypeError. I made a small jsfiddle to replicate this: https://jsfiddle.net/cgdmewkn/.

The README.md mentions that the `Vuetify object must be set in window.vuetify` but I'm not sure how to achieve that. 

I would greatly appreciate a working jsfiddle!

**Comment by iliyaZelenko** [comment]
I tried to configure this for an hour, but could not. [Here](https://jsfiddle.net/ilyaZelen/sx5zoy73/72/) is the code I ended up with.

In general, the `tiptap` itself apparently does not support CDN, I could not find it in the documentation and other sources. So apparently this is a problem in the `tiptap` itself.

**Comment by djhuistra** [comment]
Thanks a lot for your effort in to try tot get it to work! It is unfortunate that it seems to be a `tiptap` issue, but that is also good to know.

**Comment by renedekat** [comment]
@djhuistra In your main.js file you need to import the plugin

`import { TiptapVuetifyPlugin } from 'tiptap-vuetify';
Vue.use(TiptapVuetifyPlugin, {
  // the next line is important! You need to provide the Vuetify Object to this place.
  vuetify, // same as "vuetify: vuetify"
  // optional, default to 'md' (default vuetify icons before v2.0.0)
  iconsGroup: 'fa'
});`
 
Then you can use it in your component as described in step 2 https://vuejsexamples.com/wysiwyg-editor-for-vuetify-component-simplifies-integration-tiptap-with-vuetify/
