### ISSUE TITLE
Tree-shaking mdi-js vuetify?

### ISSUE THREAD

**Issue by ctmqwe** [iliyaZelenko/tiptap-vuetify#150]
According to recommendations, use of mdi/js icons in production - better solution is tree-shaking. How to inject icon imports in tiptap plugin?

**Comment by iliyaZelenko** [comment]
Currently 3 types of icons are available: md, fa, mdi, mdiSvg (from the `@mdi/js` package). Only those icons that the editor uses will be used, that is, your prod bundle will not have extra icons.

[Here ](https://github.com/iliyaZelenko/tiptap-vuetify/blob/master/src/extensions/nativeExtensions/Blockquote.ts#L20) is an example of how the editor uses icons.
