### ISSUE TITLE
Add onFocus-Event

### ISSUE THREAD

**Issue by saschamander** [iliyaZelenko/tiptap-vuetify#154]
I saw that tiptap natively supports the onFocus-Event.

Would it be possible to have an event emitted on that?
That would be awesome! :)

**Comment by iliyaZelenko** [comment]
Hi, good idea. Whoever has the opportunity, can do PR, there is an [example of PR](https://github.com/iliyaZelenko/tiptap-vuetify/pull/161), where the same thing is done, but for the `blur` event.

**Comment by saschamander** [comment]
Implemented and created a pull request. #183
