### ISSUE TITLE
Minimize Bundle Size in Nuxt

### ISSUE THREAD

**Issue by andyfensham** [iliyaZelenko/tiptap-vuetify#157]
This is not really an issue, but I am using tiptap-vuetify in nuxt and my bundle size is very big.  I would like to see if I can reduce it, but don't know how.

**Comment by tvld** [comment]
What is very big? I also use nuxt and I have about 3MB in total... Seems ok to me ?

**Comment by mrfrase3** [comment]
Hey, just looked into this issue for our project.

The main bundle isn't being optimised in the releases, causing it to be ~ 900kB, It seems nuxt wont try to optimise it if it is over 500kB, a fix is to use the common.js bundle instead (~390kB):

`import { TiptapVuetifyPlugin } from 'tiptap-vuetify/dist/bundle-cjs';`

or clone locally, add `optimize: true` for `bundle-esm.js` in the `rollup.config.js` file, and run the build, you can then use the smaller (~340kB) `/dist/bundle-esm.js` file.

**Comment by iliyaZelenko** [comment]
Bundle is optimized in #169

**Comment by tvld** [comment]
Great, thanks ))
