### ISSUE TITLE
Floating Menu

### ISSUE THREAD

**Issue by tvld** [iliyaZelenko/tiptap-vuetify#159]
I do not seem to get [floating menu](https://tiptap.scrumpy.io/floating-menu) to work. When I try the code listed there, I get error in Tiptap ``[Vue warn]: Error in data(): "ReferenceError: document is not defined"`` in Tiptap. Any example of hos this obvious thing would work?

**Comment by vedantmamgain** [comment]
They haven't integrated it. They've made only the bubble menu and the basic toolbar.

![image](https://user-images.githubusercontent.com/17256082/83946347-c0cee280-a82d-11ea-8bec-dcb756fb6049.png)

**Comment by tvld** [comment]
yes, I got that too... I ended up not using this lib and used Tiptap with my one Vuetify )

**Comment by vedantmamgain** [comment]
Have you implemented the floating menu?

**Comment by tvld** [comment]
yes, but again not using this lib anymore. Please refer to tiptap itself ))
