### ISSUE TITLE
How to use it as a component?

### ISSUE THREAD

**Issue by rancou** [iliyaZelenko/tiptap-vuetify#177]
I dont wanna include 
`<tiptap-vuetify
      v-model="content"
      output-format="html"
      :extensions="extensions"
      :card-props="{ elevation: 0, class: 'pa-0', outlined: true }"
    />`
and all other extensions on every time I need it.

So I create a component with all the content and if I need it I only have to call `<RichTextEditior />`. However, I want to bind v-model content from other component but I cant mutate props directly. I want to do something like `<RichTextEditior :content="content" />` or `<RichTextEditior v-model="content" />`  and I still want to access the content from the component that includes <RichTextEditor />. I tried things like in the component 
`<tiptap-vuetify
      v-model="content"
      output-format="html"
      :extensions="extensions"
      :card-props="{ elevation: 0, class: 'pa-0', outlined: true }"
     @keydown="$emit('save', content)"
    />`
However, keydown, for some reasons, does not include the last character when I emit. if the content is`<h1>Test</h1>` it only emits `<h1>Tes</h1>`

How to overcome this? Thanks!

**Comment by rancou** [comment]
I can just use a watcher and emit 🤦‍♂️

**Comment by iliyaZelenko** [comment]
Hi! Vue has a popular pattern called _Transparent Wrapper_, [here is a simple article](https://zendev.com/2018/05/31/transparent-wrapper-components-in-vue.html 
) on how to organize code, a very useful way. I hope you learn something new.

**Comment by herbzhao** [comment]
Sorry I am quite a noob, and I tried to follow what is outlined here: https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components
But I still fail to directly use the tiptap if imported as a sub component.. could you write a short gist?
