### ISSUE TITLE
Customize label for link input

### ISSUE THREAD

**Issue by Riaan-ZA** [iliyaZelenko/tiptap-vuetify#178]
related to this: https://github.com/iliyaZelenko/tiptap-vuetify/issues/153#issue-598118921
I need to change the label of the link input in the link dialog, `HREF` is not a very user friendly label, most people don't know what that is

**Comment by iliyaZelenko** [comment]
Hi! You can make a pull request with changing the text you think is best. [That's where this text is in English](https://github.com/iliyaZelenko/tiptap-vuetify/blob/master/src/i18n/en/index.ts#L109), you can select your [language file](https://github.com/iliyaZelenko/tiptap-vuetify/tree/master/src/i18n) if it does not match.

But I agree, it would be convenient if you could override the translation files by specifying your text in the project config.

**Comment by Riaan-ZA** [comment]
@iliyaZelenko update made for English only, don't want to make any assumptions for other languages: https://github.com/iliyaZelenko/tiptap-vuetify/pull/179#issue-420633012

**Comment by iliyaZelenko** [comment]
Done in #179
