### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by myalban** [iliyaZelenko/tiptap-vuetify#180]
Hi,

If I try to import the plugin with

`import { TiptapVuetifyPlugin } from 'tiptap-vuetify'`

I go this error 

`Could not find a declaration file for module 'tiptap-vuetify'. '//node_modules/tiptap-vuetify/dist/bundle-umd.js' implicitly has an 'any' type.
  Try `npm install @types/tiptap-vuetify` if it exists or add a new declaration (.d.ts) file containing `declare module 'tiptap-vuetify';`

Is there any declaration file for typescript ?

Best regards,
Alban

**Comment by genu** [comment]
Having this same issue. Were you able to resolve this?

I'm using Nuxt + Typescript
