### ISSUE TITLE
Custom Image Extension

### ISSUE THREAD

**Issue by mortezamohammady** [iliyaZelenko/tiptap-vuetify#194]
Hello to all and thanks from tiptap-vuetify creator, its very cool :)

I use this in my project but I have some problem with image extension, first i want to integrate the firebase storage with the tiptap and another is with image size, when i add a large image it goes out of the container and break the design and make a horizontal scroll, like this:

![ui break](https://user-images.githubusercontent.com/32927231/84598041-18e49500-ae7d-11ea-845c-9ce0a4239940.png)

i want to create a custom extension that can set the width of img tag to 100% or i should find a way to inject the style to the all images of tiptap output.

any one can help me ?
its so necessary and i should fix image problem as soon.

and another question that the image resize is in your todo list , did you complete that?

**Comment by iliyaZelenko** [comment]
Hi, @mortezamohammady!

> i want to integrate the firebase storage with the tiptap

You can use any image upload, including firebase, tiptap-vuetify has flexible system. Detailed instructions [here](https://github.com/iliyaZelenko/tiptap-vuetify#custom-image-upload-components). 

> or i should find a way to inject the style to the all images of tiptap output.

Can you try to use selector like this:

``` css
.tiptap-vuetify-editor__content img {
  width: 100%;
}
```

> and another question that the image resize is in your todo list , did you complete that?

Not yet.

**Comment by mortezamohammady** [comment]
Thanks a lot @iliyaZelenko 
I have try ``` .tiptap-vuetify-editor__content img ``` but it doesn't work and when you say this i review my code and find that i set the style tag of component to scoped and after change that it work correctly :))


and about the uploading i should

**Comment by mortezamohammady** [comment]
Hello again @iliyaZelenko  :)
i have add the firebase to my image upload system but i face to another probem 

i have change the vuetify icon system to mdi: 
```
export default new Vuetify({
  theme: {
    options: {
      customProperties: true
    },
    themes: {
      light: {
        primary: "#009688",
        secondary: "#607d8b",
        accent: "#673ab7",
        error: "#f44336",
        warning: "#ff9800",
        info: "#03a9f4",
        success: "#4caf50"
      }
    }
  },
  icons: {
    iconfont: "mdi"
  }
});

```

this is the upload dialog:
![2020-06-16 13 29 27 localhost 0a2230fa7818](https://user-images.githubusercontent.com/32927231/84755133-8952f980-afd6-11ea-9471-6be88e025a26.png)
 
as you see the close icon doesn't work with mdi.

is this a bug and i should change icon system to default or i can change the tiptap-vuetify icon system to mdi ?
