### ISSUE TITLE
Is there any getter for the value (html/json) using the EditorView instance 

### ISSUE THREAD

**Issue by Tucsky** [iliyaZelenko/tiptap-vuetify#196]
Im using the editor like this

```
<tiptap-vuetify :value="fact" :extensions="extensions" @blur="save" />

save(event, tiptapInstance) {
console.log(tiptapInstance.value) // undefined
```

(get json, get html)
I went through the doc but it doesn't looks like there is anything close to that. 
A `@change` would work too, very common to have a change event on component like that.
Im probably not using it right but Im very curious

**Comment by bensengupta** [comment]
hey, have you figured this out?

**Comment by bensengupta** [comment]
Solved, the readme should really indicate this.
```vue
<template>
  <tiptap-vuetify
    v-model="content"
    output-format="html"
    :editor-properties="{
      editorProps: {
        handleKeyPress,
      },
    }"
  />
</template>

<script>
export default {
  // ...
  methods: {
    handleKeyPress(view, event) {
      console.log(this.content);
    },
  },
};
</script>
```

**Comment by Tucsky** [comment]
> **`hey, have you figured this out?`**

I replaced :value with a  **v-model** and capture the change with a watcher, its working well
