### ISSUE TITLE
unknow custom elements: v-toolbar, v-tooltip, v-card, v-icon, v-btn

### ISSUE THREAD

**Issue by fabioebner** [iliyaZelenko/tiptap-vuetify#21]
Hei man, can U help me please?
 I not using the A La cart option in my app, 

but when I try to show the tiptap I got the error:

unknow custom elements:  v-toolbar, v-tooltip, v-card, v-icon, v-btn 

this is my vuetify.js file:

```
import Vue from "vue";
import Vuetify from "vuetify/lib";
import "vuetify/src/stylus/app.styl";
// tiptop
import { TiptapVuetifyPlugin } from "tiptap-vuetify";
import "tiptap-vuetify/dist/main.css";

Vue.use(Vuetify, {
  iconfont: "md"
});
Vue.use(TiptapVuetifyPlugin, {
  // optional, default to 'md' (default vuetify icons before v2.0.0)
  iconsGroup: "md"
});

```

And I use your sample in my component

**Comment by iliyaZelenko** [comment]
Hi, do you use vuetify-loader?

Maybe this will help: https://github.com/iliyaZelenko/tiptap-vuetify/issues/18

**Comment by fabioebner** [comment]
I not using a vuetify loader

I create the project in vue ui and  add the plugin vue-cli-plugin-vuetify ( select to not use A La cart) and he create my project with vuetify

**Comment by iliyaZelenko** [comment]
@fabioebner perhaps it is used:https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/dev/package.json#L32

In any case, I think this will help you:

```
import Vuetify, { VTooltip, VToolbar, VCard, VIcon, VBtn } from 'vuetify/lib';

Vue.use(Vuetify, {
  iconfont: "md",
  components: {
    VTooltip,
    VToolbar,
    VCard,
    VIcon,
    VBtn,
  },
});
```

**Comment by fabioebner** [comment]
Works 
but it was strange, I never needed to put any component just like that

tks anyway

**Comment by iliyaZelenko** [comment]
In future versions of this problem will not be, this is my mistake.
Thank you for using my library, I hope it will satisfy your needs. Good luck!

**Comment by fabioebner** [comment]
I thank you for the component and the help, and I'm going to open a tick for a feature: D
