### ISSUE TITLE
How to disable image upload and leave only the image link option from dialog

### ISSUE THREAD

**Issue by tnorbs** [iliyaZelenko/tiptap-vuetify#210]
Hi there,

I'm trying to disable only the image upload option on the dialog, but didn't find any solution. 

Any ideas? Thanks!

**Comment by SamuelBFavarin** [comment]
I have same issue :worried:

**Comment by tnorbs** [comment]
FYI, I was able to disable the button by adding the following script:

`hideUploadImageBtn() {
+      const uploadBtn = document.getElementsByClassName("v-tab");
+      uploadBtn[1].style.display = "none";
+      uploadBtn[2].style.pointerEvents = "none";
+    },`

**Comment by tnorbs** [comment]
FYI, I was able to disable the button by adding the following function:

`hideUploadImageBtn() {
 const uploadBtn = document.getElementsByClassName("v-tab");
 uploadBtn[1].style.display = "none";
 uploadBtn[2].style.pointerEvents = "none";
}`
