### ISSUE TITLE
Wrong language code (zh-CN)

### ISSUE THREAD

**Issue by tiaod** [iliyaZelenko/tiptap-vuetify#215]
According to the tiptap-vuetify documentation, the language code for Simplified Chinese should be `zh-CN`
![image](https://user-images.githubusercontent.com/7500825/89019214-92faab80-d34f-11ea-91bd-dc045e97ae9c.png)

However, according to the [source code](https://github.com/iliyaZelenko/tiptap-vuetify/blob/master/src/i18n/index.ts#L39), the language code is actually `zh`, which is also incorrect. It should be `zhHans`

According to the [vuetify documentation](https://vuetifyjs.com/en/customization/internationalization/#internationalization-i-18-n), Simplified Chinese should be `zhHans`
![image](https://user-images.githubusercontent.com/7500825/89019583-17e5c500-d350-11ea-94c9-fd655ac1f4f2.png)

**Comment by iliyaZelenko** [comment]
Hi, apparently you are right. I think the best solution here would be, in order not to break backward compatibility, to make an alias for `zh`: `zhHans` in the code. I will be glad to accept PR.

**Comment by tiaod** [comment]
Okay, I will write a PR later
