### ISSUE TITLE
Generate the content with styles

### ISSUE THREAD

**Issue by fabioebner** [iliyaZelenko/tiptap-vuetify#22]
A lot of people need to transform the Html into a PDF file, and uses a backend api for that (sample openhtmltopdf in java), but to export the pdf just like the editor's show the style are needed :D today I need to re-create all the style in my backend.

tks

**Comment by iliyaZelenko** [comment]
Thanks for the activity, it's nice to see that.

You could try getting styles like this:
`import cssContent from 'tiptap-vuetify/dist/main.css'` (or something similar).
Send it to backend if needed. 

By the way, in the future you will have the opportunity to create your own button in the editor, which, for example, exports to pdf.

**Comment by fabioebner** [comment]
I will try , 
but looking the .css file all style start with ".tiptap-vuetify-editor__content", for sample ".tiptap-vuetify-editor__content blockquote" (and in result html only the blockquote) 

anyway tks

**Comment by Steeve55** [comment]
Do you found a solution ? I have the same problem. I want to use the content html as body for an email but the problem is we miss the css to have the same rendering as in the tiptap editor.

**Comment by erthi16** [comment]
Remove all local styles inside your tiptap editor vue file and recreate the ones missing (like blockquote) in your App CSS override file.

**Comment by arslan-butt** [comment]
Can someone update on this issue? HOw to fix this issue?
