### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by tkoop** [iliyaZelenko/tiptap-vuetify#229]
I would like to use this component, but I can't get it to work.  I'm sorry if I'm not following instructions, but I'm trying.  I can't get this thing to appear on the page at all.  And I see a console error.

This is what I'm doing, from a clean install:

To reproduce on Mint 20:

npm --version
	#it says 6.14.4
	
vue --version
	# is says @vue/cli 4.5.6

vue create testapp
	# Pick "default (vue 2)"
	
cd testapp

vue add vuetify
	# pick the default
	
npm run serve
	# just to make sure it's working.  Yes, I see the "Welcome to Vuetify" page.
	# Ctrl-c to quit.

npm install --save tiptap-vuetify
	# it seemed to work, but I get this warning:
	# npm WARN prosemirror-utils@0.9.6 requires a peer of prosemirror-tables@^0.9.1 but none is installed. You must install peer dependencies yourself.
	
npm run serve
	# just to make sure it's working.  Yes, I still see the "Welcome to Vuetify" page.
	# Ctrl-c to quit.
	

Then I replace the contents of App.vue with the contents mentioned on this page: https://github.com/iliyaZelenko/tiptap-vuetify.  I copy and paste in everything from &lt;template&gt; to &lt;/script&gt; in the section "NPM (ES modules) step 2. Use in your component. Here is a complete example:"

But the page in my browser is now blank and I see this message in the console:

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'framework' of undefined"

found in

---> <N>
       <App> at src/App.vue
         <Root>
```

I must be doing something wrong.  Please help me.  I want to use this very nice component.  Thank you.

**Comment by majkshkurti** [comment]
@tkoop I got the same problem.  I fixed it by adding as a plugin like below:
`Vue.use(TiptapVuetifyPlugin, {vuetify})`

**Comment by tkoop** [comment]
Hey!  Thanks Majk!  It works!

In case anyone else sees this, make sure these lines are in your main.js:

```
import { TiptapVuetifyPlugin } from 'tiptap-vuetify';
Vue.use(TiptapVuetifyPlugin, {vuetify});
```
