### ISSUE TITLE
How to add TodoItem,TodoList in tiptap-vuetify?

### ISSUE THREAD

**Issue by qwtfy** [iliyaZelenko/tiptap-vuetify#248]
### Bug
> [Vue warn]: Error in mounted hook: "TypeError: Class constructor Node cannot be invoked without 'new'"

### app.vue 
```
<template>
  <v-container>
    <tiptap-vuetify
      v-model="content"
      :extensions="extensions" />

  </v-container>
</template>
 
<script>

// import the component and the necessary extensions
import { TiptapVuetify, Heading, Bold, Italic, Strike, Underline, Code, Paragraph, BulletList, OrderedList, ListItem, Link, Blockquote, HardBreak, HorizontalRule, History ,TodoList,TodoItem} from 'tiptap-vuetify'
 
export default {
  // specify TiptapVuetify component in "components"
  components: { TiptapVuetify },

  data: () => ({
    content: `
      <h3>TIPTAP</h3>`,
    // declare extensions you want to use
    extensions: [
      History,
      Blockquote,
      Link,
      Underline,
      Strike,
      Italic,
      ListItem,
      BulletList,
      OrderedList,
      [Heading, {
        options: {
          levels: [1, 2, 3]
        }
      }],
      Bold,
      Code,
      HorizontalRule,
      Paragraph,
      HardBreak,
      TodoList,
      [TodoItem, {
        options: {nested: true}
      }],],  
  }),}
</script>
```

### System information

 - OS: Windows10 
 - version of Node.js:v14.15.1

### Dependencies

-  "core-js": "^3.6.5",
-  "tiptap-vuetify": "^2.24.0",
-  "vue": "^2.6.11",
-  "vuetify": "^2.2.11"

### repo
[todo-List issue][1]

  [1]: https://github.com/qwtfy/tiptap-vuetify

**Comment by JDevFrame** [comment]
adding tiptap to transpileDependencies in vue.config.js resolved the issues with untranspiled classes for me. 
like this
```
transpileDependencies: [
    /[\\/]node_modules[\\/]tiptap.*/
],
```

**Comment by qwtfy** [comment]
@JDevFrame  thanks did it for me too

**Comment by Steeve55** [comment]
Thank you very much :)

**Comment by d11-jwaring** [comment]
This fixed it for me also, thanks!

**Comment by matletix** [comment]
And if you use the webpack-dev-server, you need to restart it after making the change (hot reloading is not sufficient).

**Comment by nimonimonimo** [comment]
So in my project I am not use vue-cli but instead webpack encore to build the frontend. Could anyone advice me how to enable transpiling of dependencies as vue.config.js is not parsed?
