### ISSUE TITLE
How to change the locale dynamically ?

### ISSUE THREAD

**Issue by Steeve55** [iliyaZelenko/tiptap-vuetify#259]
When we set the locale dynamically for vuetify like that : this.$vuetify.lang.current = 'fr', the locale of tiptap plugin is not updated..

So, I tried everything to change dynamically the locale but impossible.. Can you help me or fix the problem please ?

Thank you.

**Comment by vincentauger** [comment]
Just ran into this myself. Currently, the code loads all localisation once and does not monitor the current vuetify locale after load. While this is not ideal in our cases, the best way to do this dynamically now is to provide the current locale as a key to the component like so:

```vue
<tiptap-vuetify
                :key="$vuetify.lang.current"
                v-model="value"
                :card-props="cardProps"
                :extensions="extensions"
                :disabled="disabled"
            >
```

This will force a reload of the tiptap-vuetify component on locale change and load the new locale in. Hope it helps.
