### ISSUE TITLE
Can't access store in TipTap custom Image component NuxtJS

### ISSUE THREAD

**Issue by nuolmakara16** [iliyaZelenko/tiptap-vuetify#277]
0

I was trying to implement custom image upload components which was describe in the tiptap-vuetify document https://www.npmjs.com/package/tiptap-vuetify#custom-image-upload-components in my nuxtjs project. Everything works perfectly until I try to access store using this.$store And it say undefined. Can someone tell me what should I do to access the nuxt store?

**Comment by MOTA9100** [comment]
i have same problem, i made file manager component from before, in there i use `this.$axios` to load files from server. when i want to use my component, and i can not access to `$axios`

**Comment by nuolmakara16** [comment]
@MOTA9100  I actually got this problem solved! I forgot to close!

**Comment by MOTA9100** [comment]
what is the solution?

**Comment by nuolmakara16** [comment]
### I create new js file inside store folder 

![image](https://user-images.githubusercontent.com/58760973/126876889-af5506ad-a06f-4ae1-8191-0f8b758ee214.png)

### and this is ckeditor component

![image](https://user-images.githubusercontent.com/58760973/126877045-22f5a495-53de-487a-9baa-8c04e8d701e3.png)

### and then this is how you use ckeditor

![image](https://user-images.githubusercontent.com/58760973/126876998-652dfcc5-cf69-46d1-bd02-0338841726cc.png)

Hope this might help!

**Comment by nuolmakara16** [comment]
@MOTA9100 its not working?

**Comment by MOTA9100** [comment]
@nuolmakara16 this is about CkEditor not tiptap-vuetify :|

**Comment by nuolmakara16** [comment]
@MOTA9100 I got confused!

**Comment by MOTA9100** [comment]
we can access to $store, $vuetify, $axios and other modules in custom image component with `window.$nuxt.xxx`. remember that as before know we can do this just in client side
