### ISSUE TITLE
Cannot read property 'vuetifyLang' of undefined"

### ISSUE THREAD

**Issue by Proroks** [iliyaZelenko/tiptap-vuetify#33]
Добрый день! Подскажите пожалуйста в чём может быть проблема?  Cannot read property 'vuetifyLang' of undefined" ошибка в console

**Comment by iliyaZelenko** [comment]
Привет, спасибо что используете мой пакет!

Мне кажется вы не правильно поставили этот пакет.

Убедитесь что у вас похожий код:
```js
import Vue from 'vue'
import { TiptapVuetifyPlugin } from 'tiptap-vuetify'
// стили
import 'tiptap-vuetify/dist/main.css'

// это должно быть первым
Vue.use(Vuetify)
// ПОСЛЕ Vue.use(Vuetify) !!!
Vue.use(TiptapVuetifyPlugin)
```

Если не помогло, то не моглим бы вы скинуть свой код? (с `Vue.use`, например).

**Comment by EnOane** [comment]
Такая же беда после обновления vuetify до 2.0.5

**Comment by EnOane** [comment]
`tiptap-vuetify: Could not determine language, because Vue.prototype.$vuetifyis not available. Using language "en" by default.`

Такая ошибка вылетает еще

**Comment by EnOane** [comment]
Проблема в том, что vuetify 2.0 недоступна как $vuetify во Vue. prototype

**Comment by iliyaZelenko** [comment]
@EnOane это не ошибка, а предупреждение. Оно тебе en язык поставило из-за того что не нашло языка в $vuetify. Если хочешь поменять язык, то можешь изменить  `$vuetify.lang = 'ru'`. Эта проблема не связана с этим issue.

**Comment by EnOane** [comment]
@iliyaZelenko согласен, но с 2.0 vuetify так не сделаешь, потому что `Vue.prototype.$vuetify = undefined` Не могу пока понять почему.

**Comment by iliyaZelenko** [comment]
@EnOane в версии 2 кажется не убрали `$vuetify`, если зайти на [страницу релизов](https://github.com/vuetifyjs/vuetify/releases) и искать "$vuetify", то можно найти что они что-то изменяют/добавляют в это свойство. 
Может ты Vuetify не правильно подключил?

**Comment by EnOane** [comment]
Это с 1.5.7
![image](https://user-images.githubusercontent.com/21095265/62904213-9b995100-bd8f-11e9-9246-fb13df249471.png)


Это с 2.0
![image](https://user-images.githubusercontent.com/21095265/62904120-51b06b00-bd8f-11e9-8757-4df3f251a6b1.png)

**Comment by iliyaZelenko** [comment]
Вижу там не только в tiptapVuetifyPlugin нет vuetify, а ещё в самом Vue.prototype, хоть на первом скриншоте они оба есть. Не могу ничего точно сказать. Но даже если доку открыть, то там есть `$vuetify`. Попробуй по другому поставить Vuetify.

**Comment by idrys** [comment]
![Zrzut ekranu 2019-08-14 o 14 08 47](https://user-images.githubusercontent.com/13288094/63020002-2d42b480-be9d-11e9-8831-437bfbc200b2.png)

**Comment by iliyaZelenko** [comment]
@idrys you use Vuetify 2?

**Comment by idrys** [comment]
yes

**Comment by JiaweiTan** [comment]
Hi, i'm facing the same issue too.
In vuetify.js, I have included the following code.
`import en from 'vuetify/es5/locale/en'`
`export default new Vuetify({
  lang: {
    locales: { en },
    current: 'en',
  },
}
`
But it's still not working. it show this error
> Could not determine language, because Vue.prototype.$vuetifyis not available. Using language "en" by default.

**Comment by iliyaZelenko** [comment]
@JiaweiTan hi, what started to show new is a warning, not an error. For more confidence, I want to clarify, are you using vuetify 2?

**Comment by JiaweiTan** [comment]
@iliyaZelenko Hi. Thanks for the quick reply. Yes, I am using vuetify 2.

**Comment by rosnaib11** [comment]
I'm having a same issue using vuetify 2.1.3 `Cannot read property 'vuetifyLang' of undefined`

**Comment by cwiggan** [comment]
I am using version 1 and Getting the error when running a jest test "TypeError: Cannot read property 'vuetifyLang' of undefined"
