### ISSUE TITLE
[Docs] Provide documentation for integrating with Nuxt js

### ISSUE THREAD

**Issue by Haider8** [iliyaZelenko/tiptap-vuetify#42]

**Comment by iliyaZelenko** [comment]
In theory, you need to create a separate Nuxt's [plugin](https://nuxtjs.org/api/configuration-plugins/#plugins) where to write the code from the [first paragraph](https://github.com/iliyaZelenko/tiptap-vuetify#get-started), though the Vuetify object needs to be imported from another file (most likely it's also Nuxt's plugin). 

More or less like this:

**/plugins/tiptapVuetify.js**
```js
import Vue from 'vue'
// import Vuetify object
import { vuetify  } from '~/plugins/vuetify'
// import TiptapVuetify plugin
import { TiptapVuetifyPlugin } from 'tiptap-vuetify'
// don't forget to import CSS styles
import 'tiptap-vuetify/dist/main.css'

Vue.use(TiptapVuetifyPlugin, {
  // the next line is important! You need to provide the Vuetify Object to this place.
  vuetify,
  iconsGroup: 'md'
})
```

**nuxt.config.js**

```js
export default {
  plugins: ['~/plugins/vuetify', '~/plugins/tiptapVuetify']
}
```

**Comment by iliyaZelenko** [comment]
Added a lot more information with demo [here](https://github.com/iliyaZelenko/tiptap-vuetify#nuxt).
