### ISSUE TITLE
Vuetify 2.X Support

### ISSUE THREAD

**Issue by Maxchii** [iliyaZelenko/tiptap-vuetify#43]
Tried to get the package working for Vuetify 2.0 but with no luck.
Are there currently any workarounds or ETA on official 2.0 support?

**Comment by iliyaZelenko** [comment]
I look this library is gaining momentum. **This week** I will try to add support for Vuetify 2. With the new version of this package, there will also come many other cool changes. 

Thanks to everyone for supporting the project. ❤️

**Comment by Maxchii** [comment]
Much appreciated! looking forward to seeing 2.0 support.
