### ISSUE TITLE
Button Icons not Rendering

### ISSUE THREAD

**Issue by olivergiess** [iliyaZelenko/tiptap-vuetify#53]
Hello,

Thank you for managing this component, it is excellent!

I am having issues integrating into my project. The Icons for buttons are not rendering, for example I attempted to use only the Bold extension and instead of a **B** being rendered as per the demo I have the string **FORMAT_BOLD** rendered.

I attempted to look under the hood myself but it is above my current Vue/Javscript skill level.

Are there any suggestions I saw another ticket with a similar issue though it was closed without explanation.

Edit: No errors in my console.

**Comment by olivergiess** [comment]
I realised that I did not have the correct icons configured.

`Vue.use(TiptapVuetifyPlugin, {
  vuetify,
  iconsGroup: 'mdi'
})
`

I had to set iconsGroup to `'mdi'` instead of `'md'`.

**Comment by iliyaZelenko** [comment]
Hi, thank you very much for using the component! I'm glad that you found a solution, I regret that I could not answer faster.

Maybe the documentation is written a little confusing, which caused you problems. I am very sorry for your time.

Perhaps in the next version I will make automatic detection of the `iconsGroup`, as [this is set in the Vuetify itself](https://vuetifyjs.com/en/customization/icons#usage). 

Write if you still have questions or suggestions for improvement, I am glad to help. 😃

**Comment by shawn-p-m** [comment]
@iliyaZelenko Also, big fan of yours!

the documentation specifically says:
iconsGroup: 'md'

but it should say:
iconsGroup: 'mdi'

Maybe I'll make a quick pr
