### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by MrSunshyne** [iliyaZelenko/tiptap-vuetify#58]
I have a UI built in dark mode as the primary interface. I followed the instructions to include vuetify-tip-tap and it worked great ! Except that I can't figure out how to switch the theme without touching the CSS directly. 

A prop to switch between light / dark mode would be awesome !

**Comment by iliyaZelenko** [comment]
Hi, thank you very much for using the package!

I rewrited the [example](https://codesandbox.io/s/tiptap-vuetify-wysiwyg-editor-6p9wp?fontsize=14&initialpath=%2Fcustom-toolbar&module=%2Fsrc%2Fexamples%2FCustomToolbar.vue) a bit, now there is a version with a black theme, it is quite easy to do if this is what you need.

![](https://i.imgur.com/PV0FjZM.png)

**Comment by MrSunshyne** [comment]
That's absolutely perfect.
Thanks for the awesome package @iliyaZelenko  !
