### ISSUE TITLE
Syntax error when trying to import tiptap-vuetify in nuxt

### ISSUE THREAD

**Issue by noobling** [iliyaZelenko/tiptap-vuetify#60]
![image](https://user-images.githubusercontent.com/23206864/66669904-12b56d80-ec8b-11e9-89a5-79a54af26f8d.png)

I tried it using v2.2. Webpack for nuxt doesn't seem to like the `export` which comes with the compiled code.

https://codesandbox.io/s/codesandbox-nuxt-9e17n

**Comment by iliyaZelenko** [comment]
Yes, I see, interesting. I think the reason is that I forgot to use the Babel here on build.

I tried to do:

```js
  build: {
    transpile: ['tiptap-vuetify'],
  }
```

But it didn’t help. I will solve this one as soon as possible, thanks for the reproduction!

**Comment by iliyaZelenko** [comment]
I understood what the problem was, I really spent 4 hours on it, now I’m thinking how best to solve it. I am well acquainted with Nuxt, but this is not an easy situation. Hope this is not so urgent for you.

**Comment by noobling** [comment]
That's okay what was the problem?

**Comment by iliyaZelenko** [comment]
The solution was quite simple, although there were a lot of nuances.

I added to the [documentation](https://github.com/iliyaZelenko/tiptap-vuetify#nuxt) how to use it with Nuxt, there you will also find an example on Codesanbox.

In total, I spent 12 hours on this, ahah, but most importantly I helped you 😄 .

**Comment by noobling** [comment]
Thanks so much for your work 🥳🥳
