### ISSUE TITLE
mdiSvg icon support needed

### ISSUE THREAD

**Issue by avanishp2** [iliyaZelenko/tiptap-vuetify#62]
I am working on project which uses mdiSvg icons. So this editor will not work with the existing project of vuetify which uses mdiSvg.
I tried below code for configuration:
```
import Vue from 'vue'
import { TiptapVuetifyPlugin } from 'tiptap-vuetify'
import 'tiptap-vuetify/dist/main.css'

export default ({ app }) => {
    Vue.use(TiptapVuetifyPlugin, {
        vuetify: app.vuetify,
        iconsGroup: 'mdiSvg'
    })
}
```
Output:

![image](https://user-images.githubusercontent.com/29193513/67076422-bbdbf680-f1aa-11e9-86b0-9e4562f73037.png)

Vuetify components support mdiSvg icons and so this editor should also support it
I am using Nuxt 2.10.0 and @nuxt/vuetify 1.9.0 package for my project.

**Comment by iliyaZelenko** [comment]
Ok, I’ll try to do it today or tomorrow, could you please wait? Thanks for using my package!

**Comment by iliyaZelenko** [comment]
It is now available in the new version 🎉, thanks for waiting.
