### ISSUE TITLE
[Question] Height for textarea

### ISSUE THREAD

**Issue by websitevirtuoso** [iliyaZelenko/tiptap-vuetify#84]
How to set up height for textarea? not toolbar

**Comment by iliyaZelenko** [comment]
By default, the height depends on the content. If you need to specify the maximum height after which the scroll will appear for the content (textarea), then you need to apply such styles:

``` css
.tiptap-vuetify-editor__content {
  max-height: 200px;
}
```

Hope this helps.

**Comment by thebspin** [comment]
How do i solve this using scoped css? I want to be able to have different heights on certain pages. Ofcourse i could wrap the editor but i think there should be props for certain styling stuff maybe?

**Comment by iliyaZelenko** [comment]
@thebspin ok, I'll do it for you today or tomorrow. I’ll call it `max-height`.

**Comment by thebspin** [comment]
@iliyaZelenko I would also like to request a min-height so that I could make the initial field larger. I would be happy to do a pr tomorrow if there is some free time at work and you could point me to the right files.

**Comment by iliyaZelenko** [comment]
[Here](https://github.com/iliyaZelenko/tiptap-vuetify/blob/master/src/components/TiptapVuetify.vue#L39) is the key element.
You can give dynamic styles: `:style="contentDynamicStyles"`. Then in class:

``` js
// this is computed in TypeScript
get contentDynamicStyles () {
  return <code based on props>
}
```

**Comment by thebspin** [comment]
Hi i tried something and wantred to test it.
After running dev however i get this error in my console:

```
ERROR  Failed to compile with 1 errors                                                                                                                                                                             9:38:28 AM
This relative module was not found:

* ../dist/main.css in ./demo/main.js
```

I am relatively new to TS but i don't think this error is caused because of my inexperience in that... could you tell me what could be wrong?

**Comment by iliyaZelenko** [comment]
Looks like you did everything right. This is my fault: [this line](https://github.com/iliyaZelenko/tiptap-vuetify/blob/master/demo/main.js#L18) needs to be changed to `import '../src/main.css'`. Should work.

**Comment by thebspin** [comment]
```
ERROR  Failed to compile with 1 errors                                                                                                                                                                             1:21:34 PM
This relative module was not found:

* ../src/main.css in ./demo/main.js
```
Still gives an issue i am afraid... I also dont see a css file in the src folder, do i have to build it first?

**Comment by iliyaZelenko** [comment]
I really did not see that there is no css in this folder, I'm sorry. Just comment out this line with css import.

**Comment by thebspin** [comment]
I made a PR, i think everything should be okay.

**Comment by iliyaZelenko** [comment]
It was made in #99 (a long time ago) by @thebspin, thanks again.

**Comment by saidulhaqueriaz** [comment]
Here is my solution:
.tiptap-vuetify-editor .ProseMirror {
  min-height: 200px;
}

**Comment by KevinKreps** [comment]
This is very interesting. I have set the min-height on the div, but now the cursor is completely bugged when dragging elements. Anyone having the same problem?

**Comment by cycle4passion** [comment]
I tried

```css
.ProseMirror {
  min-height: 100%;
}
```
Which did not work, any suggestion there?

**Comment by fpaupier** [comment]
@cycle4passion, try to add an [overflow-y](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y) property, did the trick for me:
```css
.ProseMirror {
  min-height: 150px;
  max-height: 200px;
  overflow-y: auto;
```

**Comment by ferrwan** [comment]
We also can make the height resizable by adding `resize` so it can be more dynamic

```scss
// .scss
.tiptap-vuetify-editor__content {
  resize: vertical;
  transition: all 2s, height 0s; // keep the existing style transition except the height so no laggy behavior when resizing

  .ProseMirror {
    height: 100%; // To make the content clickable along the height
  }
}
```

**Comment by yadi09** [comment]
How to set up height for textarea? 
here is my code i tried:
`{/* 📝 Text Editor */}`
`<div className="border border-gray-300 rounded-lg p-3 bg-white shadow-md min-h-[200px] h-auto"> `
 `        <EditorContent editor={editor} className="h-full max-h-[200px]" /> `
`</div>`

And here is the Output the style = h-full max-h-[200px] **### NOT Work:**

![Image](https://github.com/user-attachments/assets/22c501e5-f8bc-41bf-ac56-e1b596bc8590)
