### ISSUE TITLE
Edit HTML output by an Extensions

### ISSUE THREAD

**Issue by olivergiess** [iliyaZelenko/tiptap-vuetify#85]
Hello,

Are we in anyway able to edit the HTML output by an extension e.g. `Paragraph`

Instead of:

`<p>Hello, World!</p>`

We could output

`<p class="white--text">Hello, World!</p>`

I believe this feature would greatly increase flexibility of this package, allowing The use of Vuetify helper classes for styling. Currently we have to reimplement the styling in custom CSS selectors wrapping the output of the WYSIWYG.

**Comment by iliyaZelenko** [comment]
Hi, interesting idea. 

This editor is based on [tiptap](https://github.com/scrumpy/tiptap), I think you can somehow do it, but you need to ask the author tiptap. 

If he gives an answer to how to do this, then I will implement what you ask. At the moment, I can not imagine how to do this. 

I looked at the source code a bit, [that’s where the paragraph is](https://github.com/scrumpy/tiptap/blob/master/packages/tiptap/src/Nodes/Paragraph.js), but I don’t see the possibility of giving a default class here.
