### ISSUE TITLE
Toolbar not rendering

### ISSUE THREAD

**Issue by sandroden** [iliyaZelenko/tiptap-vuetify#9]
Hi,

I tried to integrate `tiptap-vuetify` in my vuetify project but the toolbar doesn't render... so I tried to study you example on codesandbox.io and I can't see where the difference is. So I tried to recreate your example again in [codesandbox.it](https://codesandbox.io/s/x7l72xvp3z) and... the toolbr doesn't render. Do you have any idea on what's happening?

Thanks in advance

**Comment by sandroden** [comment]
In the codesandbox.io I prepared was sufficent to upgrade vuetify to a version >= 1.4 for the toolbar to appear. In my project no.

**Comment by iliyaZelenko** [comment]
Hi,

Could you please provide a screenshot of what you call "toolbar doesn't render"? Perhaps there are some errors in the console? Or maybe the editor just does not display icons?

> In the codesandbox.io I prepared was sufficent to upgrade vuetify to a version >= 1.4 for the toolbar to appear.

It seems the editor does not support a version below 1.4, I checked it.

Just in case, here is your example on codesanbox that works: https://codesandbox.io/s/2z03jr83r

Any information would be helpful, thank you for using my package.

**Comment by sandroden** [comment]
Now I managed to make render correctly. I didn't have the time to analyze what was the problem. I close the ticket as it works and will add a comment if I find out what was wrong.
