### ISSUE TITLE
Toolbar not toggling with Dark Theme

### ISSUE THREAD

**Issue by lexxyungcarter** [iliyaZelenko/tiptap-vuetify#90]
Very nice package, however, I have an issue.

When switching to dark theme, the toolbar remains the light version (while the icons shift to the dark theme style), making it hard to view the icons. Any workaround for this? It would be nice if the package would internally check if vuetify dark theme is enabled.

**Comment by iliyaZelenko** [comment]
Thanks for using my package! I’ll be happy to help.

I think this should works:

``` vue
<tiptap-vuetify
  v-model="content"
  :extensions="extensions"
  :toolbar-attributes="toolbarAttrs"
/>
```

``` js
computed: {
  toolbarAttrs () {
    return this.$vuetify.theme.isDark
      ? { color: 'black', dark: true }
      : { color: 'yellow' }
  }
}
```

I can try to make the default color of the toolbar (`'grey lighten-4'`) change depending on the `$vuetify.theme.isDark`, thanks for the idea.

**Comment by lexxyungcarter** [comment]
@iliyaZelenko That would very helpful. thanks in advance.
