### ISSUE TITLE
v-model not working with output-format="json"

### ISSUE THREAD

**Issue by deka** [iliyaZelenko/tiptap-vuetify#94]
Hi,
two-way binding (v-model) not working with output-format="json"
If i re-load json, i see the json, not the result

![image](https://user-images.githubusercontent.com/349156/68315706-74b19900-00b8-11ea-9b59-3f8f6bd0a434.png)

Regards

**Comment by iliyaZelenko** [comment]
Interesting, I'll see what is the reason.

**Comment by iliyaZelenko** [comment]
I tried `output-format="json"` and it worked correctly for me. 

Could you provide a reproduction or at least more information about the problem, please?

> If i re-load json, i see the json, not the result

I do not understand.

**Comment by deka** [comment]
Hi,
I commit reproduction in your demo : [here]( https://github.com/deka/tiptap-vuetify/commit/cbf6185b6ef68359af46f53e05d8847548adaea3)

to reproduce : 
write something, click switch, write something, click switch -> json is displayed  

PS: if you remove output-format="json", it work as expected

Regards

**Comment by t-itzel** [comment]
I also want to use v-model with a JSON value but value prop in TipTapVuetify is defined as String which causes a warning:
> [Vue warn]: Invalid prop: type check failed for prop "value". Expected String with value "[object Object]", got Object

If i pass serialized json content, the warning is gone but the editor content displays the serialized value like seen in screenshot above.

Just insert json content into v-model for reproduction:

```
<template>
    <tiptap-vuetify output-format="json" v-model="editorContent"></tiptap-vuetify>
</template>
<script>
    data: () => ({
        editorContent: {"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"This is a "},{"type":"text","marks":[{"type":"bold"}],"text":"test"}]}]}
    })
</script>
```
