### ISSUE TITLE
 Link extension : mdiSvg icon (close) not displayed

### ISSUE THREAD

**Issue by deka** [iliyaZelenko/tiptap-vuetify#95]
Hi,

![image](https://user-images.githubusercontent.com/349156/68315912-d5d96c80-00b8-11ea-8f47-084aa637a30a.png)

Regards

**Comment by iliyaZelenko** [comment]
Ok, I guessed that there would be such a problem. I will fix it today or tomorrow. Can you please wait?

**Comment by deka** [comment]
> Ok, I guessed that there would be such a problem. I will fix it today or tomorrow. Can you please wait?

No problem, i'm not production ready

**Comment by The4thLaw** [comment]
It's not limited to mdiSvg, I also have the issue with the mdi icon font.
And I can wait as well :)

Thanks

**Comment by iliyaZelenko** [comment]
Looks like this has already been fixed, this is duplicate of this [issue](#130).
