### ISSUE TITLE
Extension Link : I18n french issue

### ISSUE THREAD

**Issue by deka** [iliyaZelenko/tiptap-vuetify#96]
Hi,

I don't understand 'proche'. What did you mean ? 
![image](https://user-images.githubusercontent.com/349156/68316020-04efde00-00b9-11ea-83c1-ab29800b65db.png)

Regards

**Comment by iliyaZelenko** [comment]
Hi, 

This translation was not made by me, but by [this person](https://github.com/iliyaZelenko/tiptap-vuetify/pull/39).

If you have the best translation option, then [here](https://github.com/iliyaZelenko/tiptap-vuetify/blob/98fe71122505b48f70a727cfd37562435de0794e/src/i18n/fr/index.ts#L112) are the translations. [Here](https://github.com/iliyaZelenko/tiptap-vuetify/blob/master/src/i18n/en/index.ts#L112) is a sample in English. "Proche" should mean the button to close the modal window, maybe here an error.
