### ISSUE TITLE
[Feature Request] : prop disabled

### ISSUE THREAD

**Issue by deka** [iliyaZelenko/tiptap-vuetify#98]
Hi,
I need to enable and disable editing dynamically.
I try `:editor-properties="{ editable: false}"` but it's not pleasing.
If i understand, editor properties are added to constructor, and not dynamically, and toolbar is not disabled.

I think something like : `:disabled="disabled"`

**Comment by iliyaZelenko** [comment]
WOW, I have never had so much activity in one hour from one person, stop finally! I'm kidding. 😄 

Currently you can set `editable` dynamically for editor: 
``` js
this.editor.setOptions({
  editable: this.editable,
})
```

To get Editor you can use [`@init`](https://github.com/iliyaZelenko/tiptap-vuetify#init) event.

But it would also be nice to add styles, such as gray text. I will need to make `disabled` prop where everything will be included. Thanks for the idea.
